---
title: "Schedule"
subtitle: "Spring 2026"
format:
  html:
    include-in-header: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

---

```{r}
#| include: false
library(tidyverse)
library(htmltools)
```


```{r echo = FALSE}
schedule <- tribble(
  ~`week`, ~topic, ~`readings`, ~ `assignments`,
  "2.03.25", 'What does JEDI look like? Conceptual Foundations', '⦾ <a href="https://www.tandfonline.com/doi/full/10.1080/26939169.2025.2526628">Diversity, Equity, and Inclusion in Introductory Statistics Courses: Results from a National Survey</a> <br> ⦾ <a href="https://data-feminism.mitpress.mit.edu/pub/ei7cogfn/release/4?readingCollection=0cd867ef">Data Feminism – Chapter 2</a> <br> (first read <a href = "https://data-feminism.mitpress.mit.edu/pub/frfa9szd/release/6#e5s6oqhfqy" target = "_blank">this bullet-point summary</a> of the seven key principles of the book) <br> ⦾ <a href = "https://pmc.ncbi.nlm.nih.gov/articles/PMC3828951/" target = "_blank">Adapting Western Research Methods to Indigenous Ways of Knowing</a>',
  'identify topic, type of educational material to create, and data source',

 "2.24.25", 'What is JEDI, and how do we integrate it into our teaching materials?', '⦾ <a href="https://www.tandfonline.com/doi/full/10.1080/26939169.2025.2507366#abstract">Bringing Interdisciplinary Data Science Education Challenges into the Classroom</a> <br> ⦾ <a href="https://www.tandfonline.com/doi/full/10.1080/26939169.2023.2276446#abstract">Causal Inference Is Not Just a Statistics Problem</a>',
  ' ',

  
 "3.03.25", 'Why? - Present and Current Examples', '⦾ <a href="https://www.superdatascience.com/podcast/sds-727-unmasking-a-i-injustice-with-dr-joy-buolamwini">Unmasking A.I. Injustice, with Dr. Joy Buolamwini</a> <br> ⦾ <a href="https://www.tandfonline.com/doi/full/10.1080/26939169.2025.2485239">Moral Machine Learning: Teaching a Course at the Intersection of Applied Statistics and Moral Philosophy</a> <br> ⦾ <a href="https://www.nationalacademies.org/read/26803/chapter/8">Lived Experiences and Other Ways of Knowing in STEMM</a> <br> ⦾ <a href="https://www.youtube.com/watch?v=W4ZOFinXrJ0">Advancing Antiracism, Diversity, Equity, & Inclusion in STEMM Organizations</a>',
  ' ',
 
  "3.24.25", 'What if it goes wrong?', 'Racial microaggressions and difficult dialogues on race in the classroom (Sue et al., 2009)
Teachers’ concerns about inclusive education and the links with teachers’ attitudes (Jury et al., 2023)
Diversity, Equity, Inclusivity (DEI): Perspectives and Activities from Statistics Programs in US Higher Education (Jimmy D., 2025)
', ' ',
 
  "4.07.25",  ' ', ' ', 'participants share their current resource, peer reviews',
 
  "4.21.25",  ' ', ' ', 'presentations of resources'
  
)
```


```{r}
#| echo: false
#| column: page
# can also use column: screen-inset also the entire page??
# can use column: page for the entire page
# can use column: body-outset to bleed outside the center column of text
schedule |> 
  gt::gt() |> 
  gt::fmt_markdown(columns = everything()) |> 
    gt::cols_width(week ~ pct(10),
                 everything() ~ pct(30))
```




