---
title: "Additional Papers"
subtitle: "Spring 2026"
format: html
---



## Extra papers to read

As with all reading groups, we identified many more excellent papers than we have time to read together.
We've included a list of recommended reading for you to engage with in your spare time.


* All of <a href="https://data-feminism.mitpress.mit.edu/">Data Feminism</a>, by Catherine D'Ignazio and Lauren Klein.
* <a href = "https://nycstandswithstandingrock.wordpress.com/wp-content/uploads/2016/10/linda-tuhiwai-smith-decolonizing-methodologies-research-and-indigenous-peoples.pdf" target = "_blank">Decolonizing Methodologies: Research and Indigenous Peoples</a> by Linda Tuhiwai Smith.
* <a href = "https://nni.arizona.edu/our-work/research-policy-analysis/indigenous-data-sovereignty-governance" target = "_blank">Indigenous Data Sovereignty & Governance</a>, Collaboratory for Indigenous Data Governance.
* <a href = "https://doi.org/10.1080/26939169.2025.2507366" target = "_blank">Bringing Interdisciplinary Data Science Education Challenges into the Classroom</a> by 
Zofia Bednarowska-Michaiel and Emma Uprichard.
* <a href = "https://doi.org/10.1080/26939169.2025.2526628" target = "_blank">Diversity, Equity, and Inclusion in Introductory Statistics Courses: Results from a National Survey</a>, by Heather Barker, Kirsten Doehler, and Julia Walter.
* Advancing Antiracism, Diversity, Equity, and Inclusion in STEMM Organizations: Beyond Broadening Participation <a href="https://www.nationalacademies.org/read/26803/chapter/8">Lived Experiences and Other Ways of Knowing in STEMM</a>, National Academies of Science, Engineering and Medicine.


## Papers which might spark an idea for a JEDI-CAUSE resource

In addition, we found that the following papers might spark ideas for potential lessons you could create for the <a href = "https://causeweb.org/jedi/" target = "_blank">JEDI-CAUSE</a> website.

* <a href = "https://doi.org/10.1080/26939169.2023.2276446" target = "_blank">Causal Inference is Not Just a Statistics Problem</a> by Lucy D'Agostino McGowan, Travis Gerke, and Malcolm Barrett.
Based on their `quartet` R package, you might derive a JEDI-focused in-class activity to engage with causal models.

* <a href = "https://doi.org/10.1080/26939169.2023.2249969" target = "_blank">Culturally Relevant Data in Teaching Statistics and Data Science</a> by Travis Weiland and Immanuel Williams.
They provide ways to find and create culturally relevant datasets to use in the classroom.
You might find one or more datasets and create an activity based on the data.
Alternatively, you might create an activity on finding culturally relevant data.

* <a href = "https://docs.google.com/document/d/1UK3HFQv-3qMDNjvt0fFPbts38ApOL7ghpPE0iSYJ1Z8/edit?tab=t.0#heading=h.bfyxplihlmjs" target = "_blank">Great list of teaching strategies</a>, how could you use the list to create a resource for others? 


